package com.parkinglksnext.repository

import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import com.parkinglksnext.Reservation
import com.parkinglksnext.util.Resource
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

/**
 * Repository for reservation CRUD operations in Firestore.
 * Collection: reservations/{autoGeneratedId}
 */
class ReservationRepository {

    private val db: FirebaseFirestore = FirebaseFirestore.getInstance()
    private val collection = db.collection("reservations")

    /**
     * Real-time listener for active reservations of a given user.
     * Query: where userId == uid AND status == "active"
     */
    fun getActiveReservations(userId: String): Flow<Resource<List<Reservation>>> = callbackFlow {
        val listener = collection
            .whereEqualTo("userId", userId)
            .whereEqualTo("status", "active")
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    trySend(Resource.Error(error.localizedMessage ?: "Error al cargar reservas"))
                    return@addSnapshotListener
                }
                val reservations = snapshot?.documents?.mapNotNull { doc ->
                    doc.toObject(Reservation::class.java)?.copy(id = doc.id)
                } ?: emptyList()
                trySend(Resource.Success(reservations))
            }
        awaitClose { listener.remove() }
    }

    /**
     * Real-time listener for reservation history (completed + cancelled).
     * Ordered by createdAt descending.
     */
    fun getReservationHistory(userId: String): Flow<Resource<List<Reservation>>> = callbackFlow {
        val listener = collection
            .whereEqualTo("userId", userId)
            .whereIn("status", listOf("completed", "cancelled"))
            .orderBy("createdAt", Query.Direction.DESCENDING)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    trySend(Resource.Error(error.localizedMessage ?: "Error al cargar historial"))
                    return@addSnapshotListener
                }
                val reservations = snapshot?.documents?.mapNotNull { doc ->
                    doc.toObject(Reservation::class.java)?.copy(id = doc.id)
                } ?: emptyList()
                trySend(Resource.Success(reservations))
            }
        awaitClose { listener.remove() }
    }

    /**
     * Create a new reservation document (auto-generated ID).
     */
    fun createReservation(reservation: Reservation): Flow<Resource<Unit>> = flow {
        emit(Resource.Loading())
        try {
            val data = reservation.copy(
                createdAt = java.time.Instant.now().toString()
            )
            collection.add(data).await()
            emit(Resource.Success(Unit))
        } catch (e: Exception) {
            emit(Resource.Error(e.localizedMessage ?: "Error al crear reserva"))
        }
    }

    /**
     * Update specific fields of a reservation (e.g., startTime, endTime).
     */
    fun updateReservation(id: String, updates: Map<String, Any?>): Flow<Resource<Unit>> = flow {
        emit(Resource.Loading())
        try {
            collection.document(id).update(updates).await()
            emit(Resource.Success(Unit))
        } catch (e: Exception) {
            emit(Resource.Error(e.localizedMessage ?: "Error al actualizar reserva"))
        }
    }

    /**
     * Cancel a reservation by setting its status to "cancelled".
     */
    fun cancelReservation(id: String): Flow<Resource<Unit>> = flow {
        emit(Resource.Loading())
        try {
            collection.document(id).update("status", "cancelled").await()
            emit(Resource.Success(Unit))
        } catch (e: Exception) {
            emit(Resource.Error(e.localizedMessage ?: "Error al cancelar reserva"))
        }
    }

    /**
     * Extension: suspend until a Firestore Task completes.
     */
    private suspend fun <T> com.google.android.gms.tasks.Task<T>.await(): T =
        suspendCancellableCoroutine { continuation ->
            addOnCompleteListener { task ->
                if (task.isSuccessful) {
                    continuation.resume(task.result)
                } else {
                    continuation.resumeWithException(
                        task.exception ?: Exception("Tarea de Firestore fallida")
                    )
                }
            }
            addOnCanceledListener { continuation.cancel() }
        }
}
